#!/bin/bash
# shortcut script to Bootstrap the step deployer
# Bootstrapping is deploying itself from a local environment
set -e

go build . # Build step for your operating system

# Build step (called lambda) for linux lambda
GOOS=linux go build -o lambda
zip lambda.zip lambda

# execute step to bootstrap itself
./step bootstrap -lambda "coinbase-step-deployer" -step "coinbase-step-deployer" -states "$(./step json)"
