#!/bin/bash
# shortcut script to Deploy the step deployer
# So this uses the Step executable to call out to the Step Deployer
# which is a Step Function to deploy itself
set -e

go build . # Build step for your operating system

# Build step (called lambda) for linux lambda
GOOS=linux go build -o lambda
zip lambda.zip lambda

./step deploy -lambda "coinbase-step-deployer" -step "coinbase-step-deployer" -states "$(./step json)"
