[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/aws/aws-lambda-go"
  version = "1.1.0"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.13.6"
